#!/bin/sh

# source our profile if needed
[ -z "$USERPROFILE_CURRENT" -a -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile"

# check if the proper shell is sourcing this file
case "$SHNAME" in
    bash) ;;
       *) . "$ENV"; return 0 ;;
esac

# enable vi editing mode
set -o vi

# bash settings
shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend
shopt -s huponexit
shopt -s xpg_echo

# if not running interactively, don't do anything else
case "$-" in
    *i*) ;;
      *) return 0 ;;
esac

# functions
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions"

# if we have access to the 'stty' binary, specify args for it
command -v stty >/dev/null 2>&1 && stty -ixon

# default prompt
case "$TERM" in
    linux|*color*) PS1="\[\033[1;35m\]\\u@\\h\[\033[0m\]:\[\033[1;34m\]\\w\[\033[0m\]\\\$ " ;;
                *) PS1="\\u@\\h:\\w\\\$ " ;;
esac

# set it using set_ps1 if the shell supports it
PROMPT_COMMAND="set_ps1"

# load ~/.config/shell/aliases
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases"

# load scripts in bashrc.d
[ -d "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bashrc.d" ] && {
    for i in ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bashrc.d/*.sh; do
        [ -r "$i" ] && . "$i"
    done
}
