#!/bin/sh

# additional functionality and compatibility layers
# simple scripts in ~/.local/share/bin are also reimplemented here

# `source` is just a bashism for `.` anyways
command -v source >/dev/null 2>&1 || eval "alias source='.'"

# rudimentary 'unset' for shells that don't have it
command -v unset >/dev/null 2>&1 || eval 'unset() {
    for _k in "$@"; do
        eval "$_k="
    done
}'

# rudimentary 'local' for shells that don't have it
command -v local >/dev/null 2>&1 || eval 'local() {
    for _kv in "$@"; do
        _key="${_kv%%=*}"; _val="${_kv##$_key=}"; eval "$_key=\"\$_val\""
    done
}'

# rudimentary 'seq' for environments that don't have it
command -v seq >/dev/null 2>&1 || seq() {
    start="$1"
    while [ "$start" -lt "$2" ]; do
        printf "$start\n"; start="$((start+1))"
    done
}

# rudimentary `which` implementation for environments that don't have it
command -v which >/dev/null 2>&1 || which() {
    IFS=":"
    for dir in $PATH; do
        test -x "$dir/$1" && printf "%s\n" "$dir/$1" && return 0
    done
    IFS="$(printf ' \t\n')"
    return 1
}

# abbreviate a path
pathabbrev() {
    case "$1" in
        "$HOME"*) printf "~${1##$HOME}" ;;
               *) printf "$1" ;;
    esac
}
