#!/bin/sh

# posix-compatible shell init file

# source our profile if needed
test -z "$USERPROFILE_CURRENT" -a -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile" && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile"

# if not running interactively, don't do anything else
case "$-" in
    *i*) ;;
      *) return 0 ;;
esac

# enable vi editing mode
set -o vi

# if we have access to the 'stty' binary, specify args for it
command -v stty >/dev/null 2>&1 && stty -ixon

# load ~/.config/shell/aliases
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases"

# load scripts in rc.d
[ -d "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shrc.d" ] && {
    for i in ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shrc.d/*.sh; do
        [ -r "$i" ] && . "$i"
    done
}
