#!/bin/sh

# yash init file; todo: look at https://github.com/magicant/yash/blob/trunk/share/initialization/common

# source our profile if needed
[ -z "$USERPROFILE_CURRENT" -a -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile"

# check if the proper shell is sourcing this file
case "$SHNAME" in
    yash) ;;
       *) . "$ENV"; return 0 ;;
esac

# enable vi editing mode
set -o vi

# if not running interactively, don't do anything else
case "$-" in
    *i*) ;;
      *) return 0 ;;
esac

# functions
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions"

# if we have access to the 'stty' binary, specify args for it
command -v stty >/dev/null 2>&1 && stty -ixon

# default prompt
case "$TERM" in
    linux|*color*) PS1="$(printf "\[\033[1;35m\]\${USER:-\$LOGNAME}\@\${HOSTNAME:-\$(hostname 2>/dev/null || cat /proc/sys/kernel/hostname 2>/dev/null || printf \"localhost\")}\[\033[0m\]:\[\033[1;34m\]\$(pathabbrev \"\$PWD\")\[\033[0m\]\\\$ ")" ;;
                *) PS1="\${USER:-\$LOGNAME}\${HOSTNAME:+@\$HOSTNAME}:\$(pathabbrev \"\$PWD\")\\\$ " ;;
esac

# set the PS1 using set_ps1 if the shell supports it
PROMPT_COMMAND="set_ps1"

# load ~/.config/shell/aliases
[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases"

# load scripts in rc.d
[ -d "${XDG_CONFIG_HOME:-$HOME/.config}/shell/yashrc.d" ] && {
    for i in ${XDG_CONFIG_HOME:-$HOME/.config}/shell/yashrc.d/*.sh; do
        [ -r "$i" ] && . "$i"
    done
}
