#!/bin/sh

# theme template for riverwm

# set background and border color
riverctl background-color 0x#::rootbg::#
riverctl border-color-focused 0x#::brightbg2::#
riverctl border-color-unfocused 0x#::statusbg::#
