#!/bin/sh

# theme template for riverwm

# set background and border color
riverctl background-color 0x${theme_wm_rootbg}
riverctl border-color-focused 0x${theme_brightbg2}
riverctl border-color-unfocused 0x${theme_statusbg}
