#!/bin/sh

# update env
command -v dbus-update-activation-environment >/dev/null 2>&1 && riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY"

# print riverwm pid
printf "$$\n" >>"/tmp/river.compositor.$LOGIN_PID"

# start yambar
command -v yambarr >/dev/null 2>&1 && (command -v yambar >/dev/null 2>&1 && yambarr </dev/null >&0 2>&0 &:) || (command -v yambar >/dev/null 2>&1 && yambar </dev/null >&0 2>&0 & printf "$!\n" >"/tmp/yambar.session.$LOGIN_PID")

# start waybar
test -z "$(cat "/tmp/yambar.session.$LOGIN_PID")" && command -v waybar >/dev/null 2>&1 && waybar </dev/null >&0 2>&0 & printf "$!\n" >>"/tmp/waybar.session.$LOGIN_PID"

# allow another instance of way-displays
test -r "/tmp/way-displays.pid" && rm "/tmp/way-displays.pid"

# start way-displays
command -v way-displays >/dev/null 2>&1 && (way-displays </dev/null >&0 2>&0 & printf "$!\n" >"/tmp/way-displays.session.$LOGIN_PID";:) && sh -c 'sleep 2; rm /tmp/way-displays.pid' </dev/null &

# start pipewire
#test -z "$(ps -Aeo user,comm | sed -ne "/^$USER\s\+\(pipewire\|wireplumber\|pulseaudio\)$/p")"
command -v pipewire >/dev/null 2>&1 && test -z "$(cat "/tmp/pipewire.session.$LOGIN_PID")" && pipewire </dev/null >&0 2>&0 & printf "$!\n" >>"/tmp/pipewire.session.$LOGIN_PID"

# kill these cmds on exit
riverctl map normal Super+Shift Q spawn 'kill $(cat /tmp/*.session.$LOGIN_PID); rm /tmp/*.session.$LOGIN_PID /tmp/river.compositor.$LOGIN_PID; riverctl exit'

# load config if possible
test -r "${XDG_CONFIG_HOME:-$HOME/.config}/river/config" && . "${XDG_CONFIG_HOME:-$HOME/.config}/river/config"

# start rivertile
riverctl default-layout rivertile
exec rivertile -main-location left -main-ratio 0.5 -view-padding 4 -outer-padding 4
