live_config_reload = true

[env]
TERM = "xterm-256color"

[debug]
log_level = "Off"

[window]
#opacity = 0.925
opacity = 1.0
dimensions = { columns = 80, lines = 24 }
decorations = "None"
blur = false
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "Dark"
resize_increments = true
title = "Terminal"

[font]
normal = { family = "${theme_font_monospace}" }
bold_italic = { style = "BoldItalic" }
size = ${theme_terminal_font_size}
builtin_box_drawing = true

[colors.primary]
background = "#${theme_mainbg}"
foreground = "#${theme_mainfg}"
bright_foreground = "#${theme_brightfg}"
dim_foreground = "#${theme_darkfg}"

[colors.normal]
black = "#${theme_mainbg}"
red = "#${theme_mainred}"
green = "#${theme_maingreen}"
yellow = "#${theme_mainyellow}"
blue = "#${theme_mainblue}"
magenta = "#${theme_mainmagenta}"
cyan = "#${theme_maincyan}"
white = "#${theme_mainfg}"

[colors.bright]
black = "#${theme_brighterbg}"
red = "#${theme_brightred}"
green = "#${theme_brightgreen}"
yellow = "#${theme_brightyellow}"
blue = "#${theme_brightblue}"
magenta = "#${theme_brightmagenta}"
cyan = "#${theme_brightcyan}"
white = "#${theme_brightfg}"

[colors.dim]
black = "#${theme_brighterbg}"
red = "#${theme_darkred}"
green = "#${theme_darkgreen}"
yellow = "#${theme_darkyellow}"
blue = "#${theme_darkblue}"
magenta = "#${theme_darkmagenta}"
cyan = "#${theme_darkcyan}"
white = "#${theme_darkfg}"

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[bell]
animation = "Linear"
duration = 0
color = "#${theme_brightfg}"

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
thickness = 0.10
